### ISSUE TITLE
kube-score/ignore ignored on pod definition.

### ISSUE THREAD

**Issue by ssebbass** [zegl/kube-score#102]
**Describe the bug**
`kube-score/ignore`annotation ignored on pod definition.

**To Reproduce**

`kube-score score pod.yaml`

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: "release-name-chart-test-connection"
  labels:
    app.kubernetes.io/name: chart
  annotations:
    kube-score/ignore: pod-networkpolicy,pod-probes
spec:
  containers:
    - name: wget
      image: busybox:1
      command: ['wget']
      args:  ['release-name-chart:80']
      imagePullPolicy: Always
      resources:
        limits:
          cpu: 100m
          memory: 64Mi
        requests:
          cpu: 50m
          memory: 32Mi
  restartPolicy: Never
```

**Expected behavior**
No error should be returned.

**Version**
kube-score version: 0.5.0
