### ISSUE TITLE
Should throw error on invalid label values

### ISSUE THREAD

**Issue by warmfusion** [zegl/kube-score#130]
**Which version of kube-score are you using?**

> kube-score version: registry.gitlab.com/warmfusion/kube-score:0-7-0

**What did you do?**

Validated the following yaml with an invalid label value;
```yaml
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  labels:
    app.kubernetes.io/managed-by: "engineering/kustomize"
spec:
  type: ExternalName
  externalName: alertmanager.example.com
```

**What did you expect to see?**

A critical error indicating that the value of the label is not compatible with kubernetes.

**What did you see instead?**

No mention of any errors;

```
$ cat test.yaml
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  labels:
    app.kubernetes.io/managed-by: "engineering/kustomize"
spec:
  type: ExternalName
  externalName: alertmanager.example.com


$ docker run -it --rm -v $(pwd):/app registry.gitlab.com/warmfusion/kube-score:0-7-0 kube-score score /app/test.yaml
v1/Service alertmanager
    [OK] Stable version
    [OK] Service Targets Pod
    [OK] Service Type


$ docker run -it --rm -v $(pwd):/app registry.gitlab.com/warmfusion/kube-score:0-7-0 kube-score version
kube-score version: 0.7.0, commit: bc8f6ac008072bea3c33707f9d4a58265b1de30c, built: 2019-04-28T13:03:35Z
```
