### ISSUE TITLE
Openshift objects validation

### ISSUE THREAD

**Issue by andywow** [zegl/kube-score#142]
Hello, it will be nice, if kube-score will validate openshift objects: Route (Ingress analog) and DeploymentConfig (Deployment analog)

**Comment by zegl** [comment]
Hey, I’m not very familiar with OpenShift, but I don’t see any reason for why this project should not support it. Pull Requests are welcome.

**Comment by 030** [comment]
@andywow Could you indicate what `Kind` of OpenShift objects should be validated, e.g. BuildConfigs, DeploymentConfigs, ImageStreams, Routes. I think that we should to validate one.

**Comment by 030** [comment]
@zegl could you give me some pointers? For example, an OpenShift DeploymentConfig is the equivalent of a Deployment in k8s. Should I create a new file? What is the best way to start in this project?

```
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: frontend
spec:
  replicas: 5
  selector:
    name: frontend
  template: { ... }
  triggers:
  - type: ConfigChange 
  - imageChangeParams:
      automatic: true
      containerNames:
      - helloworld
      from:
        kind: ImageStreamTag
        name: hello-openshift:latest
    type: ImageChange  
  strategy:
    type: Rolling      
```
Source: https://docs.openshift.com/container-platform/4.1/applications/deployments/what-deployments-are.html
