### ISSUE TITLE
Named ports are not supported

### ISSUE THREAD

**Issue by ludovicm67** [zegl/kube-score#144]
**Which version of kube-score are you using?**

> kube-score version: 0.7.1

**What did you do?**

I was writing some manifests file to describe a service for one of my Kubernetes cluster. I used named ports. When I apply the manifests it works perfectly, but my CI which use `kube-score` seems not to be happy.

Here is a simple example manifest:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: nginx
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.17.1
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: nginx
  name: nginx
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app.kubernetes.io/name: nginx
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/name: nginx
  name: nginx
spec:
  rules:
  - host: nginx.my-cluster.local
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx
          servicePort: http
```

And run the following command:

```sh
kube-score score manifest.yaml \
    --ignore-test pod-probes \
    --ignore-test deployment-has-host-podantiaffinity \
    --ignore-test container-security-context \
    --ignore-test pod-networkpolicy \
    --ignore-test deployment-has-poddisruptionbudget \
    --ignore-test container-resources
```

It fails.

If I change the `servicePort` from `http` to `80` in the Ingress and remove the `name` of the port specified in the Service, then it will pass.

**What did you expect to see?**

Here is the output I got when I use numerical ports instead of named ones:

```
extensions/v1beta1/Ingress nginx
    [OK] Ingress targets Service
    [OK] Stable version
apps/v1/Deployment nginx
    [OK] Stable version
    [OK] Container Image Tag
    [OK] Container Image Pull Policy
v1/Service nginx
    [OK] Stable version
    [OK] Service Type
    [OK] Service Targets Pod
```

It should give the same output using numerical or named ports.

**What did you see instead?**

```
extensions/v1beta1/Ingress nginx
    [CRITICAL] Ingress targets Service
        * / -> No service match was found
             No service with name nginx and port 0 was found
    [OK] Stable version
apps/v1/Deployment nginx
    [OK] Stable version
    [OK] Container Image Tag
    [OK] Container Image Pull Policy
v1/Service nginx
    [OK] Stable version
    [OK] Service Targets Pod
    [OK] Service Type
```
