### ISSUE TITLE
Security Context at PodLevel not evaluated

### ISSUE THREAD

**Issue by mrueg** [zegl/kube-score#146]
**Which version of kube-score are you using?**

> kube-score version: [e.g. 0.3.0]

master

**What did you do?**
See: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  labels:
    app: test
spec:
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      securityContext:
        fsGroup: 65534
        runAsUser: 65534
      containers:
      - name: test
```

**What did you expect to see?**

securityContext from PodLevel gets recognized as a ContainerLevel securityContext

**What did you see instead?**
kube-score recommends to set a ContainerLevel securityContext
