### ISSUE TITLE
Defining policyTypes should not be required in NetworkPolicy

### ISSUE THREAD

**Issue by petvaa01** [zegl/kube-score#180]
**Which version of kube-score are you using?**

kube-score version: kube-score version: 1.2.1, commit: c108212e8f04339127cb40de0b619185f61aa348, built: 2019-08-20T10:27:04Z

**What did you do?**

Run kube-score on network policy without `policyTypes` defined. 

https://kubernetes.io/docs/concepts/services-networking/network-policies/
> If no policyTypes are specified on a NetworkPolicy then by default Ingress will always be set and Egress will be set if the NetworkPolicy has any egress rules.

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: testapp-netpol
  namespace: testspace
spec:
  podSelector:
    matchLabels:
      app: testapp
  ingress:
  - ports:
    - port: 53
      protocol: TCP
    - port: 53
      protocol: UDP
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-test-1
  namespace: testspace
  labels:
    app: testapp
spec:
  containers:
  - name: foobar
    image: foo/bar:latest
```

**What did you expect to see?**

```
    [WARNING] Pod NetworkPolicy
        · The pod does not have a matching egress network policy
            Add a ingress policy to the pods NetworkPolicy
```
**What did you see instead?**

```
    [CRITICAL] Pod NetworkPolicy
        · The pod does not have a matching network policy
            Create a NetworkPolicy that targets this pod
```
