### ISSUE TITLE
Crash: readUint32 on dynamic env fields

### ISSUE THREAD

**Issue by Dentrax** [zegl/kube-score#232]
**Which version of kube-score are you using?**

> kube-score version: `kube-score_1.5.1_darwin_amd64`

**What did you do?**

1. Create _service.yml_:

```
apiVersion: v1
kind: Service
metadata:
  name: ${APP}-service
  namespace: test
spec:
  type: NodePort
  ports:
  - port: ${PORT_EXPOSE}
    targetPort: ${PORT_EXPOSE}
    nodePort: ${PORT}
  selector:
    app: ${APP}
```

2. Run: `kube-score score service.yml`

**What did you expect to see?**

> Shouldn't it recognize dynamic vars like `${...}`? 

**What did you see instead?**

> 

```
panic: v1.Service.Spec: v1.ServiceSpec.Ports: []v1.ServicePort: v1.ServicePort.NodePort: readUint32: unexpected character: �, error found in #10 byte of ...|odePort":"${PORT}","|..., bigger context ...|"namespace":"test"},"spec":{"ports":[{"nodePort":"${PORT}","port":"${PORT_EXPOSE}","targetPort":"${P|...

goroutine 1 [running]:
github.com/zegl/kube-score/parser.decode(0xc0001f81c0, 0xd9, 0xe0, 0x1bf9420, 0xc00029cd80)
	/Users/gustav/src/kube-score/parser/parse.go:166 +0xf1
github.com/zegl/kube-score/parser.decodeItem(0xc0002badf0, 0x1, 0x1, 0x0, 0x0, 0xc000298ed0, 0xc000298f00, 0x1, 0xc000279200, 0x0, ...)
	/Users/gustav/src/kube-score/parser/parse.go:251 +0x23c3
github.com/zegl/kube-score/parser.detectAndDecode(0xc0002badf0, 0x1, 0x1, 0x0, 0x0, 0xc000298ed0, 0xc000298f00, 0x1, 0xc000279200, 0xc0001f81c0, ...)
	/Users/gustav/src/kube-score/parser/parse.go:158 +0x502
github.com/zegl/kube-score/parser.ParseFiles(0xc0002badf0, 0x1, 0x1, 0x0, 0x0, 0xc000298ed0, 0xc000298f00, 0x1, 0x0, 0x1ab6891, ...)
	/Users/gustav/src/kube-score/parser/parse.go:126 +0x27d
main.scoreFiles(0x7ffeefbff508, 0xa, 0xc00018e050, 0x1, 0x1, 0x7b00000001a17780, 0xc0001dbde8)
	/Users/gustav/src/kube-score/cmd/kube-score/main.go:199 +0x74f
main.main.func1(0x7ffeefbff508, 0xa, 0xc00018e050, 0x1, 0x1)
	/Users/gustav/src/kube-score/cmd/kube-score/main.go:52 +0x60
main.main()
	/Users/gustav/src/kube-score/cmd/kube-score/main.go:80 +0x457

```
