### ISSUE TITLE
securityContext false failures when defined at pod-level vs container level

### ISSUE THREAD

**Issue by funkypenguin** [zegl/kube-score#239]
**Which version of kube-score are you using?**

> kube-score version: 1.5.1

**What did you do?**

Attempted to score a deployment manifest which included appropriate securityContext values at the pod level

Below:
```
---
# Source: cert-manager/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: RELEASE-NAME-cert-manager
  namespace: "default"
  labels:
    app: cert-manager
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: "controller"
    helm.sh/chart: cert-manager-v0.14.2
  annotations:
    kube-score/ignore: pod-probes
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cert-manager
      app.kubernetes.io/instance: RELEASE-NAME
      app.kubernetes.io/component: "controller"
  template:
    metadata:
      labels:
        app: cert-manager
        app.kubernetes.io/name: cert-manager
        app.kubernetes.io/instance: RELEASE-NAME
        app.kubernetes.io/component: "controller"
        app.kubernetes.io/managed-by: Helm
        helm.sh/chart: cert-manager-v0.14.2
    spec:
      serviceAccountName: RELEASE-NAME-cert-manager
      securityContext:
        fsGroup: 10001
        privileged: false
        readOnlyRootFilesystem: true
        runAsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001
      containers:
        - name: cert-manager
          securityContext:
            fsGroup: 10001
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 10001
            runAsNonRoot: true
            runAsUser: 10001
          image: "quay.io/jetstack/cert-manager-controller:v0.14.2"
          imagePullPolicy: Always
          args:
          - --v=2
          - --cluster-resource-namespace=$(POD_NAMESPACE)
          - --leader-election-namespace=kube-system
          - --enable-certificate-owner-ref=true
          - --namespace=letsencrypt-wildcard-cert
          - --webhook-namespace=$(POD_NAMESPACE)
          - --webhook-ca-secret=RELEASE-NAME-cert-manager-webhook-ca
          - --webhook-serving-secret=RELEASE-NAME-cert-manager-webhook-tls
          - --webhook-dns-names=cert-manager-webhook,cert-manager-webhook.default,cert-manager-webhook.default.svc
          ports:
          - containerPort: 9402
            protocol: TCP
          env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          resources:
            limits:
              cpu: 100m
              memory: 64Mi
            requests:
              cpu: 10m
              memory: 32Mi
```
**What did you expect to see?**

I expected the YAML to pass the securityContext tests, since these are defined at the pod level and therefore inherited by containers

**What did you see instead?**

Kube-score failed the manifest on the basis that container-level securityContext values were not set, ignoring the overriding pod-level settings:

```
    [CRITICAL] Container Security Context
        · cert-manager -> The container is privileged
            Set securityContext.privileged to false
        · cert-manager -> The pod has a container with a writable root filesystem
            Set securityContext.readOnlyRootFilesystem to true
```

(I'm aware of the missing networkpolicy alert, but that's not material to this issue)

I see this issue was raised, patched, and merged to master in Jul 2019 (https://github.com/zegl/kube-score/pull/147), but given that there have only been 8 commits to master since the 1.5.1 release in March, could this have regressed / failed?

Cheers!
D

**Comment by zegl** [comment]
Hey @funkypenguin.

#147 is an old bug, and the fix was shipped as of [v1.0.0](https://github.com/zegl/kube-score/releases/tag/v1.0.0).

I'm not able to reproduce this bug as of v1.5.1, is it possible that you're using an older version? What does `kube-score version` print?

---

Here's the attempt of me trying to reproduce this:

```
~/s/kube-score (master) wget https://github.com/zegl/kube-score/releases/download/v1.5.1/kube-score_1.5.1_darwin_amd64 && chmod +x kube-score_1.5.1_darwin_amd64
~/s/kube-score (master) ./kube-score_1.5.1_darwin_amd64 score issues-239.yaml
apps/v1/Deployment RELEASE-NAME-cert-manager in default                       💥
    [CRITICAL] Pod NetworkPolicy
        · The pod does not have a matching network policy
            Create a NetworkPolicy that targets this pod
```

**Comment by funkypenguin** [comment]
Sorry, I accidentally pasted you the YAML I'd been experimenting with - I'd inserted the securityContext into the container section, instead of the pod spec.

Here's another example:

```
---
# Source: external-dns/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: RELEASE-NAME-external-dns
  labels:
    app.kubernetes.io/name: external-dns
    helm.sh/chart: external-dns-2.20.10
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: external-dns
      app.kubernetes.io/instance: RELEASE-NAME
  template:
    metadata:
      labels:
        app.kubernetes.io/name: external-dns
        helm.sh/chart: external-dns-2.20.10
        app.kubernetes.io/instance: RELEASE-NAME
        app.kubernetes.io/managed-by: Helm
      annotations:
        checksum/secret: 00ce7a2a42ced20a075463e38301ab96d6124b2adda7bd188b0633afc7eaf8e4
    spec:
      securityContext:
        fsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001
      serviceAccountName: external-dns
      containers:
        - name: external-dns
          image: "docker.io/bitnami/external-dns:0.7.1-debian-10-r2"
          imagePullPolicy: "Always"
          args:
            # Generic arguments
            - --log-level=info
            - --log-format=text
            - --policy=upsert-only
            - --provider=aws
            - --registry=txt
            - --interval=1m
            - --txt-owner-id=controller-elpenguino.net
            - --source=service
            - --source=ingress
            - --source=crd
            # AWS arguments
            - --aws-zone-type=public
            - --aws-batch-change-size=1000
            - --aws-prefer-cname
          env:
            # AWS environment variables
            - name: AWS_DEFAULT_REGION
              value: eu-west-1
            - name: AWS_SHARED_CREDENTIALS_FILE
              value: /.aws/credentials
          ports:
            - name: http
              containerPort: 7979
          readinessProbe:
            failureThreshold: 6
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          livenessProbe:
            failureThreshold: 2
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
          resources:
            limits:
              cpu: 50m
              memory: 50Mi
            requests:
              cpu: 10m
              memory: 50Mi
          volumeMounts:
            # AWS mountPath(s)
            - name: aws-credentials
              mountPath: /.aws
              readOnly: true
      volumes:
        # AWS volume(s)
        - name: aws-credentials
          secret:
            secretName: RELEASE-NAME-external-dns
```

I'm on the latest kube-score 1.5.1 as downloaded from the releases section, but `kube-score version` just outputs the following:

```
root@cn1:/tmp# ./kube-score version
Usage of kube-score:
kube-score [action] --flags

Actions:
	score	Checks all files in the input, and gives them a score and recommendations
	list	Prints a CSV list of all available score checks
	version	Print the version of kube-score
	help	Print this message

Run "kube-score [action] --help" for more information about a particular command
root@cn1:/tmp#
```

**Comment by funkypenguin** [comment]
Ignore the above YAML, that's a bad example too :( This may all be user error, I'll try and dig up a working example...

**Comment by funkypenguin** [comment]
OK, here's a non-working YAML:

```
---
# Source: cert-manager/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: RELEASE-NAME-cert-manager
  namespace: "default"
  labels:
    app: cert-manager
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: "controller"
    helm.sh/chart: cert-manager-v0.14.2
  annotations:
    kube-score/ignore: pod-probes
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cert-manager
      app.kubernetes.io/instance: RELEASE-NAME
      app.kubernetes.io/component: "controller"
  template:
    metadata:
      labels:
        app: cert-manager
        app.kubernetes.io/name: cert-manager
        app.kubernetes.io/instance: RELEASE-NAME
        app.kubernetes.io/component: "controller"
        app.kubernetes.io/managed-by: Helm
        helm.sh/chart: cert-manager-v0.14.2
    spec:
      serviceAccountName: RELEASE-NAME-cert-manager
      securityContext:
        fsGroup: 10001
        privileged: false
        readOnlyRootFilesystem: true
        runAsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001
      containers:
        - name: cert-manager
          image: "quay.io/jetstack/cert-manager-controller:v0.14.2"
          imagePullPolicy: Always
          args:
          - --v=2
          - --cluster-resource-namespace=$(POD_NAMESPACE)
          - --leader-election-namespace=kube-system
          - --enable-certificate-owner-ref=true
          - --namespace=letsencrypt-wildcard-cert
          - --webhook-namespace=$(POD_NAMESPACE)
          - --webhook-ca-secret=RELEASE-NAME-cert-manager-webhook-ca
          - --webhook-serving-secret=RELEASE-NAME-cert-manager-webhook-tls
          - --webhook-dns-names=cert-manager-webhook,cert-manager-webhook.default,cert-manager-webhook.default.svc
          ports:
          - containerPort: 9402
            protocol: TCP
          env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          resources:
            limits:
              cpu: 100m
              memory: 64Mi
            requests:
              cpu: 10m
              memory: 32Mi
```

kube-score reports:

```
# kube-score score deployment.yaml
apps/v1/Deployment RELEASE-NAME-cert-manager in default                       💥
    [CRITICAL] Container Security Context
        · cert-manager -> The container is privileged
            Set securityContext.privileged to false
        · cert-manager -> The pod has a container with a writable root filesystem
            Set securityContext.readOnlyRootFilesystem to true
    [CRITICAL] Pod NetworkPolicy
        · The pod does not have a matching network policy
            Create a NetworkPolicy that targets this pod
```
