### ISSUE TITLE
Probe checks don't consider timeout values

### ISSUE THREAD

**Issue by Iristyle** [zegl/kube-score#296]
**Which version of kube-score are you using?**

> kube-score version: 1.8.1, commit: cdab99b6ee4d135bb716a92cbb91828ea28ff492, built: 2020-08-11T08:12:42Z

**What did you do?**

When defining a `livenessProbe` that uses the same command as a `readinessProbe` but with longer timeouts, kube-score generates a `CRITICAL`

For instance:

```
livenessProbe:
  httpGet:
    path: /
    port: 8080
  initialDelaySeconds: 10
  periodSeconds: 30
readinessProbe:
  httpGet:
    path: /
    port: 8080
  initialDelaySeconds: 5
```

**What did you expect to see?**

Based on the recommendations at https://srcco.de/posts/kubernetes-liveness-probes-are-dangerous.html that it's OK to use the same command, but with longer timeout values, I'd expect this to not be a critical error.

**What did you see instead?**

```
    [CRITICAL] Pod Probes
        · Container has the same readiness and liveness probe
            Using the same probe for liveness and readiness is very likely
            dangerous. Generally it's better to avoid the livenessProbe than
            re-using the readinessProbe.
            More information: https://github.com/zegl/kube-score/blob/master/README_PROBES.md
```
