### ISSUE TITLE
PodAntiAffinity ok ?

### ISSUE THREAD

**Issue by mholleville** [zegl/kube-score#301]
**Which version of kube-score are you using?**

> kube-score version: 1.8.1

**What did you do?**

I have a kubernetes deployment object with a podAntiAffinity declared but I still have this warning:

```
    [WARNING] Deployment has host PodAntiAffinity
        · Deployment does not have a host podAntiAffinity set
            It's recommended to set a podAntiAffinity that stops multiple pods from a deployment from being
            scheduled on the same node. This increases availability in case the node becomes unavailable.
```

My YAML:

```
# Source: app-automation/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-app-automation
  labels:
    app.kubernetes.io/name: app-automation
    helm.sh/chart: app-automation-0.2.0
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Tiller
spec:
  strategy: 
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
    type: RollingUpdate
    
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: app-automation
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-automation
        app.kubernetes.io/instance: release-name
    spec:
      volumes:
        - name: nginx-conf
          configMap:
            name: "nginx-conf"
      serviceAccountName: release-name-app-automation
      securityContext:
        fsGroup: 20000
        
      containers:
        - name: app-automation
          securityContext:
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsGroup: 10000
            runAsNonRoot: true
            runAsUser: 10000
            
          image: "nginx:stable"
          imagePullPolicy: Always
          env:
          - name: sample
            value: sample
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /live
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
            
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - sample
              topologyKey: kubernetes.io/hostname
            weight: 60
```

Looking at the [source code](https://github.com/zegl/kube-score/pull/78/files), there shouldn't be any reassembly warning unless I misconfigured something

**Comment by zegl** [comment]
Hey,

In this section, you're adding an affinity that this pod should preferably not be scheduled on nodes where there already is a pod with the label `app.kubernetes.io/name: sample` running. 

```
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - sample
              topologyKey: kubernetes.io/hostname
            weight: 60
```

The Pods created from this Deployment, will have the following labels:

```
        app.kubernetes.io/name: app-automation
        app.kubernetes.io/instance: release-name
```

kube-score isn't at fault here, it saved you!

To fix this, update the `matchExpression` to match pods where `app.kubernetes.io/name` is set to `app-automation`.
