### ISSUE TITLE
False-positive "Container has the same readiness and liveness probe" if `failureThreshold` differs

### ISSUE THREAD

**Issue by AndiDog** [zegl/kube-score#339]
**Which version of kube-score are you using?**

kube-score version: 1.10.0, commit: 95faa2ad082e05d8b7637d0bd5e1ae00d1550260, built: 2020-11-07T14:17:50Z

**What did you do?**

```
readinessProbe:
  tcpSocket:
    port: http
  initialDelaySeconds: 5
  periodSeconds: 5
  failureThreshold: 3
livenessProbe:
  tcpSocket:
    port: http
  initialDelaySeconds: 5
  periodSeconds: 5
  failureThreshold: 12
```

in a Deployment.

**What did you expect to see?**

No error for this part because `failureThreshold` is a very valid approach to differentiate a liveness probe, for example to kill a container if it's not ready for an extended period of time.

**What did you see instead?**

```
[CRITICAL] Pod Probes
[...]
Container has the same readiness and liveness probe
```
