### ISSUE TITLE
GitLab CI produces kube-score usage

### ISSUE THREAD

**Issue by Tulrath** [zegl/kube-score#348]
**Which version of kube-score are you using?**

kube-score version: v1.10.1

**What did you do?**

I am using kube-score in a GitLab CI pipeline with the following .gitlab-ci.yml (partial):

stages:
  - eval

kube_score:
  stage: eval
  image: zegl/kube-score:v1.10.1
  script:
    - kube-score score --output-format ci --ignore-test 'container-image-pull-policy,container-image-tag,container-resources,container-security-context,deployment-has-poddisruptionbudget,networkpolicy-targets-pod,pod-networkpolicy' kubernetes/*.yml
   
**What did you expect to see?**

When I run the same command locally, I see the expected output (I am using a lot of the ignore-flags so that I can slowly turn them on one at a time):

➜  my-service git:(checklist) kube-score score --output-format ci --ignore-test 'container-image-pull-policy,container-image-tag,container-resources,container-security-context,deployment-has-poddisruptionbudget,networkpolicy-targets-pod,pod-networkpolicy' kubernetes/*.yml
[OK] my-service apps/v1/Deployment
[OK] my-service v1/Service

**What did you see instead?**

The job failed in the GitLab CI pipeline, and produced kube-score usage in the logs:

Running with gitlab-runner 11.5.0 (3afdaba6)
  on poke 5f0b857e
Using Docker executor with image zegl/kube-score:v1.10.1 ...
Pulling docker image zegl/kube-score:v1.10.1 ...
Using docker image sha256:b3c85f5f93b5fb5c1eb157321cece836289983d7808e8a8940ab8ddc53f61a50 for zegl/kube-score:v1.10.1 ...
Running on runner-5f0c857a-project-4260538-concurrent-0 via gitlab-runner-zgcp...
00:02
Fetching changes...
00:01
HEAD is now at 640b570 feat: multi-file support for kube-score that works better with GitLab CI pipeline.
Checking out 640b5708 as checklist...
Skipping Git submodules setup
Usage of kube-score:
00:01
kube-score [action] --flags
Actions:
	score	Checks all files in the input, and gives them a score and recommendations
	list	Prints a CSV list of all available score checks
	version	Print the version of kube-score
	help	Print this message
Run "kube-score [action] --help" for more information about a particular command

**Comment by zegl** [comment]
I'm not familiar with GitLab CI, so I don't think that I can help you here. My guess is that "kube-score" is provided as the first argument to the program.

Here's an example of how to use kube-score using Docker (example from the root of kube-score):

```bash
docker run -v $(pwd)/score/testdata:/testdata zegl/kube-score:v1.10.1 score --output-format ci /testdata/all-ok.yaml
```

**Comment by OmegaVVeapon** [comment]
We use `kube-score` in our Gitlab CI pipelines. This is how:
```
kube-score:
  stage: k8s-validation
  image:
    # Can't use the smaller image because it doesn't have sh and Gitlab requires a shell to run in CI...
    # name: zegl/kube-score:latest
    name: ${DOCKER_HUB_PREFIX}/zegl/kube-score:latest-helm
    entrypoint: [""]
  dependencies:
    - render
  script:
    - "kube-score score rendered-helm.yaml"
  allow_failure: true
  ```
`rendered-helm.yaml` is just the result of `helm template` in a previous stage. Hopefully this helps.
