### ISSUE TITLE
"Ingress targets Service" panics on bad input

### ISSUE THREAD

**Issue by MikeK184** [zegl/kube-score#363]
**Which version of kube-score are you using?**
v1.11.0
v1.10.1
v1.10.0

**What did you do?**

Updated the apiVersion of an ingress.yaml file and suddenly kube-score always fails with an runtime error that looks like this:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xde364b]

goroutine 1 [running]:
github.com/zegl/kube-score/score/ingress.ingressTargetsServiceCommon(0x10caa38, 0xc0003d1d40, 0xc000331120, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/gustav/src/kube-score/score/ingress/ingress.go:36 +0x98b
github.com/zegl/kube-score/score/ingress.ingressTargetsService.func1(0x10caa38, 0xc0003d1d40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/gustav/src/kube-score/score/ingress/ingress.go:17 +0x8d
github.com/zegl/kube-score/score.Score(0x10d4478, 0xc000264c60, 0xc000237590, 0x1, 0x1, 0x0, 0x0, 0xc0002a8270, 0xc0002a82a0, 0x1, ...)
        /Users/gustav/src/kube-score/score/score.go:57 +0x179
main.scoreFiles(0x7fffed06b357, 0xa, 0xc000142020, 0x3, 0x3, 0x5, 0xc00015bf30)
        /Users/gustav/src/kube-score/cmd/kube-score/main.go:180 +0x938
main.main.func1(0x7fffed06b357, 0xa, 0xc000142020, 0x3, 0x3)
        /Users/gustav/src/kube-score/cmd/kube-score/main.go:36 +0x65
main.main()
        /Users/gustav/src/kube-score/cmd/kube-score/main.go:64 +0x3c3
```

**Bypass this error**
To begin with i had no idea why that was happening, but found out that changing the **apiVersion: extensions/v1beta1** to **apiVersion: networking.k8s.io/v1** caused this issue. However if i change the apiVersion to **networking.k8s.io/v1beta1** solves the issue again.

There is another way to make it work if you have set **apiVersion: networking.k8s.io/v1** ; for that i just changed the "paths" in the yaml file below to "path" and it worked again.

The ingress.yaml file

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "sealed-secret-ui.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "k8s.labels" . | indent 4 }}
spec:
  rules:
  - host: {{ required "Ingress Hostname is required" .Values.ingress.hostname }}
    http:
      paths:
      - backend:
          serviceName: {{ template "sealed-secret-ui.name" . }}
          servicePort: http
  tls:
  - hosts:
    - {{ .Values.ingress.hostname }}

```

**Comment by zegl** [comment]
It's annoying that kube-score panics like it did, but the reason is that `networking.k8s.io/v1` and `networking.k8s.io/v1beta1` are not actually the same, and their API:s _are_ different.

In `v1beta1` (and earlier), the backend is configured like this:

```yaml
      - backend:
          serviceName: some-service
          servicePort: http
```

While in `v1` it looks like this:

```yaml
      - backend:
          service:
            name: some-service
            port:
              name: http
```

Docs: https://kubernetes.io/docs/reference/kubernetes-api/service-resources/ingress-v1/#IngressBackend

If you would apply the configuration as you have above to a Kubernetes cluster, it likely would have screamed loudly at you. ;-)
