### ISSUE TITLE
kube-score/ignore does not work for container-security-context-readonlyrootfilesystem

### ISSUE THREAD

**Issue by jsalonen** [zegl/kube-score#373]
**Which version of kube-score are you using?**

> kube-score version: v1.10.0 and v1.11.0

**What did you do?**

Adding `kube-score/ignore` for `container-security-context-readonlyrootfilesystem` should allow kube-score to pass on containers that have non-readonly filesystem.

Example template that fails:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: statefulset-test-1
  annotations:
    kube-score/ignore: container-security-context-readonlyrootfilesystem
spec:
  template:
    spec:
      containers:
      - name: foobar
        image: foo:bar
        securityContext:
          readOnlyRootFilesystem: false
```

**What did you expect to see?**

I expect the kube-score to pass the validation for readOnlyRootFileSystem due to ignore

The template contains other errors that of course should appear

**What did you see instead?**

```
    [CRITICAL] Container Security Context
        · foobar -> The pod has a container with a writable root filesystem
            Set securityContext.readOnlyRootFilesystem to true
```
