### ISSUE TITLE
kube-score panic on empty `ingress.spec.rules.http`

### ISSUE THREAD

**Issue by Nitive** [zegl/kube-score#388]
**Which version of kube-score are you using?**

1.12.0

**What did you do?**

I'm trying to lint ingress without `.spec.rules.http` block

```yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: app-ingress
spec:
  rules:
    - host: foo.bar.network
  tls:
    - hosts:
        - foo.bar.network
```

**What did you expect to see?**

No panic. `ing.spec.rules.http` is not required by spec. We use ingresses without http block for redirects which are specified as annotations.

**What did you see instead?**

`panic: runtime error: invalid memory address or nil pointer dereference`
