### ISSUE TITLE
Feature request: Support Argo Rollouts

### ISSUE THREAD

**Issue by zidadrtl** [zegl/kube-score#430]
Would be nice to support Argo Rollouts CRD's as deployment type (now this is not recognized as a valid target reference):

For example:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: my-service
spec:
  strategy:
    canary:
      analysis:
        templates:
          - templateName: build-low-error-low-latency
        args:
          - name: service
            value: my-service
          - name: namespace
            value: my-namespace
          - name: build
            value: $(BUILD)
        startingStep: 1
      steps:
        - setWeight: 100
        - pause: {duration: 10m}
```
