### ISSUE TITLE
Feature request: Detect duplicate environment variables defined

### ISSUE THREAD

**Issue by ryo-yamaoka** [zegl/kube-score#448]
Duplicate definitions of environment variables result in unexpected behavior, which we would like to discover.
This issue is reported in the Kubernetes repo but has not yet been fixed.
https://github.com/kubernetes/kubernetes/issues/58477

## Propose behavior

```yaml
# manifest.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: envvars-deployment
  labels:
    app: envvars
  annotations:
    kube-score/ignore: pod-networkpolicy,container-resources,container-image-pull-policy,container-security-context-privileged,container-security-context-user-group-id,container-security-context-readonlyrootfilesystem,container-ephemeral-storage-request-and-limit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: envvars
  template:
    metadata:
      labels:
        app: envvars
    spec:
      containers:
      - name: envvars
        image: busybox:1.34
        command:
        - /bin/sh
        - -c
        - date; env; tail -f /dev/null
        env:
        - name: SAMPLE_ENV_VAR1
          value: sample1
        - name: SAMPLE_ENV_VAR2
          value: sample2
        - name: SAMPLE_ENV_VAR2 # WANT TO DETECT THIS
          value: sample2-duplicated
```

```
$ kube-score score manifest.yaml
apps/v1/Deployment envvars-deployment                                         💥
    [CRITICAL] Pod EnvironmentVariable
        · The pod has duplicated environment variables
            bla bla bla ...
```
