### ISSUE TITLE
Newest release(s) not respecting kube-score/ignore annotations.

### ISSUE THREAD

**Issue by Ghettoburger** [zegl/kube-score#504]
**Which version of kube-score are you using?**

> kube-score version: v1.16.0-docker-linux/amd64

**What did you do?**

We are using kube-score in our pipelines and after release 1.15/1.16 (not yet certain which, currently our image is using 1.16) kube-score doesn't respect ignore annotations. I have no tested this behavior in few projects, and i happens on all. When we use version 1.14, ignore annotations work as expected.

Failure persisted when i mimicked the ci/cd steps on my macbook using 1.16.

Example manifest:
```
---
apiVersion: v1
kind: Service
metadata:
  name: app_name-service
spec:
  selector:
    app: app_name
  ports:
    - port: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app_name-deployment
  annotations:
    kube-score/ignore: container-security-context-user-group-id, container-security-context-readonlyrootfilesystem
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app_name
  template:
    metadata:
      labels:
        app: app_name
    spec:
      containers:
        - name: app_name
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
          ports:
            - containerPort: 3000
              name: service-port
          env:
            - name: DUMMY_VAR
              value: placeholder
          readinessProbe:
            httpGet:
              port: service-port
              path: /
            initialDelaySeconds: 30
            timeoutSeconds: 5
          resources:
            limits:
              cpu: 1200m
              memory: 1Gi
              ephemeral-storage: 500Mi
            requests:
              cpu: 800m
              memory: 800Mi
              ephemeral-storage: 100Mi
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - app_name
              topologyKey: "kubernetes.io/hostname"
```

**What did you expect to see?**
When running command:
`kube-score score ./k8s/overlays/${ENVIRONMENT}/kustomized/${ENVIRONMENT}.yml --kubernetes-version "v1.21" --ignore-container-cpu-limit --ignore-test container-image-tag --ignore-test pod-networkpolicy --ignore-test deployment-has-host-podantiaffinity --exit-one-on-warning`

Expected output:
```
$ kube-score score ./k8s/overlays/${ENVIRONMENT}/kustomized/${ENVIRONMENT}.yml --kubernetes-version "v1.21" --ignore-container-cpu-limit --ignore-test container-image-tag --ignore-test pod-networkpolicy --ignore-test deployment-has-host-podantiaffinity --exit-one-on-warning
apps/v1/Deployment app_name-deployment                                      ✅
    [OK] Pod Probes
        · Container is missing a livenessProbe
            A livenessProbe can be used to restart the container if it's
            deadlocked or has crashed without exiting. It's only recommended to
            setup a livenessProbe if you really need one.
            More information: https://github.com/zegl/kube-score/blob/master/README_PROBES.md
apps/v1/Deployment app_name-server-deployment                               ✅
    [OK] Pod Probes
        · Container is missing a livenessProbe
            A livenessProbe can be used to restart the container if it's
            deadlocked or has crashed without exiting. It's only recommended to
            setup a livenessProbe if you really need one.
            More information: https://github.com/zegl/kube-score/blob/master/README_PROBES.md
networking.k8s.io/v1/Ingress app_name-ingress                               ✅
networking.k8s.io/v1/Ingress app_name-server-ingress                        ✅
policy/v1/PodDisruptionBudget app_name-pdb                                  ✅
policy/v1/PodDisruptionBudget app_name-server-pdb                           ✅
v1/Service app_name-server-service                                          ✅
v1/Service app_name-service         
```

**What did you see instead?**

```
$ kube-score score ./k8s/overlays/${ENVIRONMENT}/kustomized/${ENVIRONMENT}.yml --kubernetes-version "v1.21" --ignore-container-cpu-limit --ignore-test container-image-tag --ignore-test pod-networkpolicy --ignore-test deployment-has-host-podantiaffinity --exit-one-on-warning
apps/v1/Deployment app_name -deployment                                  💥
    [CRITICAL] Container Security Context ReadOnlyRootFilesystem
        · app_name -> The pod has a container with a writable root filesystem
            Set securityContext.readOnlyRootFilesystem to true
    [OK] Pod Probes
        · Container is missing a livenessProbe
            A livenessProbe can be used to restart the container if it's
            deadlocked or has crashed without exiting. It's only recommended to
            setup a livenessProbe if you really need one.
            More information: https://github.com/zegl/kube-score/blob/master/README_PROBES.md
apps/v1/Deployment app_name-server-deployment                               💥
    [OK] Pod Probes
        · Container is missing a livenessProbe
            A livenessProbe can be used to restart the container if it's
            deadlocked or has crashed without exiting. It's only recommended to
            setup a livenessProbe if you really need one.
            More information: https://github.com/zegl/kube-score/blob/master/README_PROBES.md
    [CRITICAL] Container Security Context ReadOnlyRootFilesystem
        · app_name-server -> The pod has a container with a writable root filesystem
            Set securityContext.readOnlyRootFilesystem to true
networking.k8s.io/v1/Ingress app_name-ingress                               ✅
networking.k8s.io/v1/Ingress app_name-server-ingress                        ✅
policy/v1/PodDisruptionBudget app_name-pdb                                  ✅
policy/v1/PodDisruptionBudget app_name-server-pdb                           ✅
v1/Service app_name-server-service                                          ✅
v1/Service app_name-service                                                 ✅
```
