### ISSUE TITLE
No support for PV

### ISSUE THREAD

**Issue by danielstankw** [zegl/kube-score#612]
I have tried using the website version.
It works great with `deployment.yaml` and `service.yaml` but it can not validate PV and PVC

Here is an example I tried

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/data

```

and 
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: manual


```

Are those resources not supported?
