### ISSUE TITLE
score: recommend setting hostname podAntiAffinity

### ISSUE THREAD

**Issue by zegl** [zegl/kube-score#77]
Recommend setting a podAntiAffinity on Deployments and StatefulSets:

Either a `preferredDuringSchedulingIgnoredDuringExecution` or a `requiredDuringSchedulingIgnoredDuringExecution` anti affinity with the `kubernetes.io/hostname` key should be set.

Setting this prevents all pods in a deployment from being scheduled on the same node if there are other nodes available.

```yaml
spec:
  template:
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
           - topologyKey: "kubernetes.io/hostname"
```
