### ISSUE TITLE
Container Image Pull Policy: does not print a description in case of error

### ISSUE THREAD

**Issue by zegl** [zegl/kube-score#79]
**Describe the bug**

The "Container Image Pull Policy" check does not print a description in case of a critical error.

**To Reproduce**

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo
  namespace: bar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foo
  template:
    metadata:
      labels:
        app: foo
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65535
        runAsGroup: 65535
        fsGroup: 65535
      containers:
      - name: foo
        image: foo:latest
        securityContext:
          readOnlyRootFilesystem: true
        resources:
          requests:
            memory: "50Mi"
            cpu: "50m"
          limits:
            memory: "100Mi"
            cpu: "100m"
```

**Expected behavior**

An explanation of why the check is failing should be returned.

**Version**
kube-score version: master
