### ISSUE TITLE
Feature: Ignore tests via object annotations

### ISSUE THREAD

**Issue by zegl** [zegl/kube-score#85]
Currently it's only possible to ignore a test on the whole test run, with the `--ignore-test` flag.

My suggestion of how to get more fine controlled ignores, is to add annotation support for this.

kube-score can look for the annotation `kube-score/ignore` in every object that it's parsing, and ignore the tests for only that object.

A full example would look like this:

```yaml
version: v1
kind: Service
metadata:
  annotations:
    kube-score/ignore: service-type,stable-version
```
